Repository Azure/iotedge-lorawan-starterkit, pull requests merged in 2021-09, with the labels that each got.

#321 Add report to tests
  .github/workflows/ci.yaml
  .github/workflows/test_report.yaml
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest

#334 Change ip to use DNS name
  .github/workflows/ci.yaml
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest

#337 Fix E2E results
  .github/workflows/ci.yaml
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest

#342 Payload was double decoded
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaPayloadDecoder.cs
Labels: SensorDecodingTest

#343 Added new issue templates
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/pull_request_template.md
Labels: enhancement

#424 Add Path filter to CI
  .github/workflows/ci.yaml
  .github/workflows/universal_decoder_ci.yaml
Labels: enhancement
