Repository Azure/iotedge-lorawan-starterkit, pull requests merged in 2021-11, with the labels that each got.

#788 Remove logging to IoT Hub that seems unused
  .github/workflows/e2e-ci.yaml
  LoRaEngine/deployment.lbs.template.json
  LoRaEngine/deployment.template.json
  LoRaEngine/deployment.test.secondary.template.json
  LoRaEngine/deployment.test.template.json
  LoRaEngine/example.env
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/ModuleConnection/ModuleConnectionHost.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/NetworkServerConfiguration.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/UdpServer.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/Logger/Logger.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/Logger/LoggerConfiguration.cs
  Template/deviceConfiguration.json
Labels: fullci

#844 Renable CI on PR
  .github/actions/rune2etest/action.yml
  .github/workflows/e2e-ci.yaml
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 3️⃣

#890 Fix station EUI
  .github/workflows/e2e-ci.yaml
  LoRaEngine/deployment.ci.aio.template.json
  LoRaEngine/deployment.ci.lbs.template.json
  LoRaEngine/modules/LoRaBasicsStationModule/start_basestation_amd64.sh
  LoRaEngine/modules/LoRaBasicsStationModule/start_basestation_arm.sh
  LoRaEngine/modules/LoRaBasicsStationModule/station.conf
Labels: fullci, SensorDecodingTest, OTAAJoinTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest

#883 Merge `TcpLogSink` into `TcpLoggerProvider`
  LoRaEngine/modules/LoRaWanNetworkSrvModule/Logger/LogSink.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/Logger/TcpLogger.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest

#887 Feature/747 custom metrics exporters
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/ApplicationInsightsMetricExporter.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/BasicsStationNetworkServerStartup.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/Processors/LnsProtocolMessageProcessor.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/MetricExporterHostedService.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/MetricRegistry.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/PrometheusMetricExporter.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/RegistryMetricExporter.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/LoRaProcessingException.cs
  Tests/Unit/NetworkServer/ApplicationInsightsMetricExporterTests.cs
  Tests/Unit/NetworkServer/LnsProtocolMessageProcessorTests.cs
  Tests/Unit/NetworkServer/MetricExporterHostedServiceTests.cs
  Tests/Unit/NetworkServer/MetricRegistryTests.cs
  Tests/Unit/NetworkServer/PrometheusMetricExporterTests.cs
Labels: fullci, SensorDecodingTest, MacTest, ClassCTest, C2DMessageTest

#918 Enable multi-concentrator E2E test in the CI
  .github/workflows/e2e-ci.yaml
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest

#935 Feature/747 raise custom metrics
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/ApplicationInsightsMetricExporter.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/BasicsStationNetworkServerStartup.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/Processors/LnsProtocolMessageProcessor.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultClassCDevicesMessageSender.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilderResponse.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoggingLoRaRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/MessageDispatcher.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/MetricRegistry.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/PrometheusMetricExporter.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/RegistryMetricExporter.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/WebSocketWriterRegistry.cs
  Tests/Common/MessageProcessorMultipleGatewayBase.cs
  Tests/Common/MessageProcessorTestBase.cs
  Tests/Common/MoqExtensions.cs
  Tests/Common/TestLoRaDeviceFactory.cs
  Tests/Common/TestMeter.cs
  Tests/Integration/ClassCCloudToDeviceMessageSizeLimitTests.cs
  Tests/Integration/ClassCIntegrationTests.cs
  Tests/Integration/KeepAliveConnectionTests.cs
  Tests/Unit/NetworkServer/ApplicationInsightsMetricExporterTests.cs
  Tests/Unit/NetworkServer/BasicsStation/DownstreamSenderTests.cs
  Tests/Unit/NetworkServer/ConcentratorDeduplicationTest.cs
  Tests/Unit/NetworkServer/DefaultClassCDevicesMessageSenderTest.cs
  Tests/Unit/NetworkServer/LnsProtocolMessageProcessorTests.cs
  Tests/Unit/NetworkServer/MetricRegistryTests.cs
  Tests/Unit/NetworkServer/PrometheusMetricExporterTests.cs
  Tests/Unit/NetworkServer/WebSocketWriterHandleTests.cs
  Tests/Unit/NetworkServer/WebSocketWriterRegistryTests.cs
Labels: SensorDecodingTest, OTAAJoinTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest
