Repository Azure/iotedge-lorawan-starterkit, pull requests merged in 2022-10, with the labels that each got.

#1934 Feature/migrate ci to new tenant
  .github/actions/deployedge/action.yml
  .github/actions/power-azure-vm/action.yml
  .github/actions/read_keyvault/action.yml
  .github/scripts/keyvault.ps1
  .github/workflows/ci.yaml
  .github/workflows/e2e-ci.yaml
  LoRaEngine/modules/LoRaBasicsStationModule/Dockerfile.amd64
  LoRaEngine/modules/LoRaBasicsStationModule/Dockerfile.arm32v7
  LoRaEngine/modules/LoRaBasicsStationModule/Dockerfile.arm64v8
  LoRaEngine/modules/LoRaBasicsStationModule/start_basicsstation.sh
  Tests/E2E/ABPTest.cs
Labels: fullci

#1937 Remove create edge function
  .github/workflows/ci.yaml
  AssemblyInfo.cs
  LoRaEngine/LoraKeysManagerFacade/CreateEdgeDevice.cs
  LoRaEngine/LoraKeysManagerFacade/FacadeStartup.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/IDeviceRegistryManager.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/IoTHubImpl/IoTHubRegistryManager.cs
  TemplateBicep/README.md
  TemplateBicep/create_device.sh
  TemplateBicep/devices.bicep
  TemplateBicep/function.bicep
  TemplateBicep/main.bicep
  Tests/Simulation/LoRaWan.Tests.Simulation.csproj
  Tests/Unit/IoTHubImpl/IoTHubRegistryManagerTests.cs
  Tools/Cli-LoRa-Device-Provisioning/BuildForRelease.ps1
  Tools/Cli-LoRa-Device-Provisioning/Cli-LoRa-Device-Provisioning.sln
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/AddGatewayOption.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/AddOptions.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/BulkVerifyOptions.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/DeviceType.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/ListOptions.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/QueryOptions.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/RemoveOptions.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/RevokeOptions.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/RotateCertificateOptions.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/UpdateOptions.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/UpgradeFirmwareOptions.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/CommandLineOptions/VerifyOptions.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/Constants.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/DefaultRouterConfig/AS923-1.json
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/DefaultRouterConfig/AS923-2.json
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/DefaultRouterConfig/AS923-3.json
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/DefaultRouterConfig/CN470RP1.json
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/DefaultRouterConfig/CN470RP2.json
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/DefaultRouterConfig/EU863.json
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/DefaultRouterConfig/US902.json
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/DeviceTags.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/Enums.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/Helpers/ConfigurationHelper.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/Helpers/ConversionHelper.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/Helpers/IoTDeviceHelper.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/Helpers/NetIdHelper.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/Helpers/ValidationHelper.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/Keygen.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/LoRaWan.Tools.CLI.csproj
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/Program.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/StatusConsole.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/TwinProperty.cs
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/appsettings.json
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/gateway-deployment-template.json
  Tools/Cli-LoRa-Device-Provisioning/LoRaWan.Tools.CLI/gateway-observability-layer-template.json
  Tools/Cli-LoRa-Device-Provisioning/README.md
  Tools/Cli-LoRa-Device-Provisioning/Tests/LoRaWan.Tools.CLI.Tests.Unit/.editorconfig
  Tools/Cli-LoRa-Device-Provisioning/Tests/LoRaWan.Tools.CLI.Tests.Unit/DeviceProvisioningTest.cs
  Tools/Cli-LoRa-Device-Provisioning/Tests/LoRaWan.Tools.CLI.Tests.Unit/JsonUtil.cs
  Tools/Cli-LoRa-Device-Provisioning/Tests/LoRaWan.Tools.CLI.Tests.Unit/LoRaWan.Tools.CLI.Tests.Unit.csproj
  Tools/Cli-LoRa-Device-Provisioning/Tests/LoRaWan.Tools.CLI.Tests.Unit/Usings.cs
Labels: fullci

#1940 Fix add label on PR
  .github/actions/rune2etest/action.yml
  .github/workflows/e2e-ci.yaml
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 1️⃣, 2️⃣, 3️⃣, MultiConcentratorTest, CupsTest, CloudDeploymentTest

#1949 Upgrade All .net versions
  Directory.Build.props
  LoRaEngine/LoraKeysManagerFacade/LoraKeysManagerFacade.csproj
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaWan.NetworkServer.csproj
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaTools.csproj
  Tests/Unit/LoraKeysManagerFacade/ConcentratorFirmwareFunctionTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 1️⃣, MultiConcentratorTest, CupsTest, CloudDeploymentTest
