Repository Azure/iotedge-lorawan-starterkit, pull requests merged in 2022-05, with the labels that each got.

#1653 Fix CI Install Step
  .github/actions/iotedgedev/entrypoint.sh
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest, LnsDiscoveryTest

#1711 Remove unused DevEUI that breaks deserialization
  LoRaEngine/LoraKeysManagerFacade/CheckPreferredGateway/PreferredGatewayExecutionItem.cs
  LoRaEngine/LoraKeysManagerFacade/CheckPreferredGateway/PreferredGatewayResult.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultClassCDevicesMessageSender.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/FunctionBundler/PreferredGatewayResult.cs
  Tests/Integration/ClassCIntegrationTests.cs
  Tests/Unit/NetworkServer/PreferredGatewayResultTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 1️⃣, 2️⃣, MultiConcentratorTest, CupsTest

#1716 Adding Clear Cache endpoint to Facade function
  LoRaEngine/LoraKeysManagerFacade/ClearLnsCache.cs
  LoRaEngine/LoraKeysManagerFacade/EdgeDeviceGetter.cs
  LoRaEngine/LoraKeysManagerFacade/FunctionsBundler/DeduplicationExecutionItem.cs
  LoRaEngine/LoraKeysManagerFacade/IEdgeDeviceGetter.cs
  LoRaEngine/LoraKeysManagerFacade/IServiceClient.cs
  LoRaEngine/LoraKeysManagerFacade/LoraKeysManagerFacadeConstants.cs
  LoRaEngine/LoraKeysManagerFacade/SendCloudToDeviceMessage/SendCloudToDeviceMessage.cs
  LoRaEngine/LoraKeysManagerFacade/ServiceClientAdapter.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/CloudControlHost.cs
  Tests/Integration/DeduplicationWithRedisIntegrationTests.cs
  Tests/Unit/LoRaTools/ApiVersionTest.cs
  Tests/Unit/LoraKeysManagerFacade/ClearLnsCacheTest.cs
  Tests/Unit/LoraKeysManagerFacade/EdgeDeviceGetterTests.cs
  Tests/Unit/LoraKeysManagerFacade/MessageDeduplicationTests.cs
  Tests/Unit/LoraKeysManagerFacade/SendCloudToDeviceMessageTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest
