Repository Azure/iotedge-lorawan-starterkit, pull requests merged in 2022-01, with the labels that each got.

#1155 added new NOTICE file Universal_Decoder_NOTICE 41066
  Samples/UniversalDecoder/NOTICE.txt
Labels: notice

#1178 Bug/1129 rssi double
  LoRaEngine/LoraKeysManagerFacade/CheckPreferredGateway/PreferredGatewayTableItem.cs
  LoRaEngine/LoraKeysManagerFacade/FunctionsBundler/FunctionBundlerRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/FunctionBundler/FunctionBundlerProvider.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/FunctionBundler/FunctionBundlerRequest.cs
  Tests/Unit/LoraKeysManagerFacade/FunctionBundlerProviderTests.cs
  Tests/Unit/LoraKeysManagerFacade/PreferredGatewayTableItemTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, CupsTest

#1119 Dwell time support for AS923
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/BasicsStationConfigurationService.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/TwinProperty.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/Cid.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/MACCommand.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/MACCommandJsonConverter.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/TxParamSetupAnswer.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/TxParamSetupRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/DwellTimeLimitedRegion.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/DwellTimeSetting.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/Region.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionAS923.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionCN470RP1.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionCN470RP2.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionEU868.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionLimits.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionManager.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionUS915.cs
  Tests/Common/TheoryDataFactory.cs
  Tests/Integration/ConcentratorDeduplicationDataMessagesIntegrationTests.cs
  Tests/Integration/DwellTimeIntegrationTests.cs
  Tests/Integration/TestDefaultLoRaRequestHandler.cs
  Tests/Unit/LoRaTools/DwellTimeLimitedRegionTests.cs
  Tests/Unit/LoRaTools/RegionAS923TestData.cs
  Tests/Unit/LoRaTools/TxParamSetupAnswerTests.cs
  Tests/Unit/LoRaTools/TxParamSetupRequestTests.cs
  Tests/Unit/NetworkServer/BasicsStation/BasicsStationConfigurationServiceTests.cs
  Tests/Unit/NetworkServer/JsonHandlers/LnsStationConfigurationTests.cs
  Tests/Unit/NetworkServer/LoRaDeviceTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1183 added new NOTICE file LNS_NOTICE 41366
  LoRaEngine/modules/LoRaWanNetworkSrvModule/NOTICE.txt
Labels: notice

#1177 Reuse `AppSessionKey`, `AppKey` and `NetworkSessionKey`
  AssemblyInfo.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/IoTHubDeviceInfo.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDeviceCache.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDeviceJoinUpdateProperties.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/Data128.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayload.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadData.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinAccept.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/OTAAHelper/OTAAKeysGenerator.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Utils/TwinCollectionExtensions.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Utils/TwinCollectionReader.cs
  Tests/Common/IntegrationTestFixtureBase.cs
  Tests/Common/SimulatedDevice.cs
  Tests/Common/TestDeviceInfo.cs
  Tests/Common/TestKeys.cs
  Tests/Common/TestUtils.cs
  Tests/E2E/ABPTest.cs
  Tests/E2E/IntegrationTestFixtureCI.cs
  Tests/E2E/LoraArduinoSerial.cs
  Tests/E2E/OTAAJoinTest.cs
  Tests/Integration/ClassCCloudToDeviceMessageSizeLimitTests.cs
  Tests/Integration/ClassCIntegrationTests.cs
  Tests/Integration/CloudToDeviceMessageSizeLimitShouldAbandonTests.cs
  Tests/Integration/CloudToDeviceMessageSizeLimitShouldAcceptTests.cs
  Tests/Integration/CloudToDeviceMessageSizeLimitShouldRejectTests.cs
  Tests/Integration/CloudToDeviceMessageTests.cs
  Tests/Integration/ConcentratorDeduplicationDataMessagesIntegrationTests.cs
  Tests/Integration/JoinSlowGetTwinTests.cs
  Tests/Integration/JoinSlowTwinUpdateTests.cs
  Tests/Integration/JoinTests.cs
  Tests/Integration/MultiGatewayTests.cs
  Tests/Integration/ParallelProcessingTests.cs
  Tests/Integration/ProcessingTests.cs
  Tests/Simulation/IntegrationTestFixtureSim.cs
  Tests/Unit/LoRaTools/TwinCollectionExtensionsTests.cs
  Tests/Unit/LoRaWan/Data128Tests.cs
  Tests/Unit/LoRaWan/KeysTests.cs
  Tests/Unit/NetworkServer/ADRMessageProcessorTest.cs
  Tests/Unit/NetworkServer/DefaultClassCDevicesMessageSenderTest.cs
  Tests/Unit/NetworkServer/DeviceLoaderSynchronizerTest.cs
  Tests/Unit/NetworkServer/FcntLimitTest.cs
  Tests/Unit/NetworkServer/IotHubDeviceInfoTests.cs
  Tests/Unit/NetworkServer/LoRaDeviceCacheTest.cs
  Tests/Unit/NetworkServer/LoRaDeviceRegistryTest.cs
  Tests/Unit/NetworkServer/LoRaDeviceTelemetryTest.cs
  Tests/Unit/NetworkServer/LoRaDeviceTest.cs
  Tests/Unit/NetworkServer/MessageProcessorJoinTest.cs
  Tests/Unit/NetworkServer/MessageProcessorSingleGatewayTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1197 Clearing the cache on re-join
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDeviceRegistry.cs
  Tests/Unit/NetworkServer/LoRaDeviceRegistryTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1202 Adding cancellation token to LoRaDeviceClient.UpdateReportedPropertiesAsync
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/ILoRaDeviceClient.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDeviceClient.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaOperationTimeWatcher.cs
  Tests/Integration/ClassCIntegrationTests.cs
  Tests/Integration/CloudToDeviceMessageTests.cs
  Tests/Integration/ConcentratorDeduplicationJoinRequestsIntegrationTests.cs
  Tests/Integration/DecoderTests.cs
  Tests/Integration/DwellTimeIntegrationTests.cs
  Tests/Integration/JoinSlowGetTwinTests.cs
  Tests/Integration/JoinSlowTwinUpdateTests.cs
  Tests/Integration/JoinTests.cs
  Tests/Integration/KeepAliveConnectionTests.cs
  Tests/Integration/MultiGatewayTests.cs
  Tests/Integration/ParallelProcessingTests.cs
  Tests/Integration/ProcessingTests.cs
  Tests/Unit/NetworkServer/ADRMessageProcessorTest.cs
  Tests/Unit/NetworkServer/FcntLimitTest.cs
  Tests/Unit/NetworkServer/LoRaDeviceTest.cs
  Tests/Unit/NetworkServer/MessageProcessorJoinTest.cs
  Tests/Unit/NetworkServer/MessageProcessorSingleGatewayTest.cs
  Tests/Unit/NetworkServer/MultiGatewayFrameCounterUpdateStrategyTest.cs
  Tests/Unit/NetworkServer/SingleGatewayFrameCounterUpdateStrategyTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1206 Reuse `Mic`
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/ConcentratorDeduplication.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/Mic.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayload.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadData.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadDataLns.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinAccept.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinRequestLns.cs
  Tests/Common/SimulatedDevice.cs
  Tests/Unit/LoRaWan/MicTests.cs
  Tests/Unit/NetworkServer/LnsProtocolMessageProcessorTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1204 Proper Mac Commands handling
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/MACCommand.cs
  Tests/Common/SimulatedDevice.cs
  Tests/E2E/ABPTest.cs
  Tests/E2E/MacTest.cs
  Tests/Integration/CloudToDeviceMessageSizeLimitShouldAbandonTests.cs
  Tests/Integration/ConcentratorDeduplicationDataMessagesIntegrationTests.cs
  Tests/Integration/DwellTimeIntegrationTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1215 Reuse `NetId`
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDeviceJoinUpdateProperties.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/MessageDispatcher.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/NetworkServerConfiguration.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/TwinProperty.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/Mic.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/NetId.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinAccept.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/OTAAHelper/OTAAKeysGenerator.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Utils/TwinCollectionExtensions.cs
  Tests/Common/SimulatedDevice.cs
  Tests/Common/TestUtils.cs
  Tests/Integration/JoinTests.cs
  Tests/Integration/ProcessingTests.cs
  Tests/Unit/LoRaTools/TwinCollectionExtensionsTests.cs
  Tests/Unit/LoRaWan/MicTests.cs
  Tests/Unit/LoRaWan/NetIdTests.cs
  Tests/Unit/NetworkServer/LoRaDeviceTest.cs
Labels: SensorDecodingTest, ABPTest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1220 Reuse `StationEui` and `JoinEui`
  LoRaEngine/LoraKeysManagerFacade/ConcentratorCredentialsFunction.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/ConcentratorDeduplication.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/TwinProperty.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinRequestLns.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Utils/TwinCollectionExtensions.cs
  Tests/Common/IntegrationTestFixtureBase.cs
  Tests/Common/SimulatedDevice.cs
  Tests/Common/TestDeviceInfo.cs
  Tests/Common/TestUtils.cs
  Tests/E2E/C2DMessageTest.cs
  Tests/E2E/CupsTests.cs
  Tests/E2E/IntegrationTestFixtureCI.cs
  Tests/E2E/LoraArduinoSerial.cs
  Tests/E2E/MacTest.cs
  Tests/E2E/MultiConcentratorTests.cs
  Tests/E2E/MultiGatewayTests.cs
  Tests/E2E/OTAAJoinTest.cs
  Tests/E2E/OTAATest.cs
  Tests/E2E/SensorDecodingTest.cs
  Tests/Integration/ConcentratorDeduplicationJoinRequestsIntegrationTests.cs
  Tests/Integration/JoinSlowGetTwinTests.cs
  Tests/Integration/JoinSlowTwinUpdateTests.cs
  Tests/Integration/JoinTests.cs
  Tests/Integration/MultiGatewayTests.cs
  Tests/Integration/ParallelProcessingTests.cs
  Tests/Integration/ProcessingTests.cs
  Tests/Simulation/IntegrationTestFixtureSim.cs
  Tests/Unit/LoRaTools/TwinCollectionExtensionsTests.cs
  Tests/Unit/NetworkServer/FcntLimitTest.cs
  Tests/Unit/NetworkServer/LnsProtocolMessageProcessorTests.cs
  Tests/Unit/NetworkServer/LoRaDeviceTest.cs
  Tests/Unit/NetworkServer/MessageProcessorJoinTest.cs
  Tests/Unit/NetworkServer/MessageProcessorSingleGatewayTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1227 Add type for `AppNonce`
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDeviceJoinUpdateProperties.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/AppNonce.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/Mic.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinAccept.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/OTAAHelper/OTAAKeysGenerator.cs
  Tests/Unit/LoRaWan/AppNonceTests.cs
  Tests/Unit/LoRaWan/MicTests.cs
  Tests/Unit/NetworkServer/MessageProcessorJoinTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1218 Simplify the deduplication cache key by using the unique DevEui
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/ConcentratorDeduplication.cs
  Tests/Common/TheoryDataFactory.cs
  Tests/Unit/NetworkServer/ConcentratorDeduplicationTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 1️⃣, MultiConcentratorTest, CupsTest

#1222 Encapsulate session key type into key calculation methods of `OTAAKeysGenerator`
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/OTAAHelper/OTAAKeysGenerator.cs
  Tests/Unit/LoRaTools/OTAAKeysGeneratorTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1226 Improve client certificate validation by validating X509ChainStatus
  .github/workflows/e2e-ci.yaml
  LoRaEngine/modules/LoRaWanNetworkSrvModule/Dockerfile.amd64
  LoRaEngine/modules/LoRaWanNetworkSrvModule/Dockerfile.amd64.debug
  LoRaEngine/modules/LoRaWanNetworkSrvModule/Dockerfile.arm32v7
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/ClientCertificateValidatorService.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/start.sh
  Tests/Unit/NetworkServer/BasicsStation/ClientCertificateValidatorServiceTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 2️⃣, MultiConcentratorTest, CupsTest

#1257 added new NOTICE file Universal_Decoder_NOTICE 41547
  Samples/UniversalDecoder/NOTICE.txt
Labels: notice

#1264 Reactivate metricscollector in CI
  .github/workflows/e2e-ci.yaml
  LoRaEngine/deployment.ci.aio.template.json
  LoRaEngine/deployment.ci.lbs.template.json
  LoRaEngine/deployment.ci.lns.eflow.template.json
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 1️⃣, 2️⃣, CupsTest

#1144 Add & use a primitive for RX delay
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaOperationTimeWatcher.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/RxDelay.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinAccept.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/Region.cs
  Tests/Unit/LoRaTools/RegionTest.cs
  Tests/Unit/LoRaWan/RxDelayTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1280 Represent FCnt as `ushort`/`uint`
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/ConcentratorDeduplication.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/FunctionBundler/FunctionBundlerProvider.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDeviceTelemetry.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/Mic.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayload.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadData.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadDataLns.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinAccept.cs
  Tests/Common/SimulatedBasicsStation.cs
  Tests/Common/SimulatedDevice.cs
  Tests/Integration/ClassCIntegrationTests.cs
  Tests/Integration/CloudToDeviceMessageTests.cs
  Tests/Integration/MultiGatewayTests.cs
  Tests/Unit/LoRaWan/MicTests.cs
  Tests/Unit/NetworkServer/ADRMessageProcessorTest.cs
  Tests/Unit/NetworkServer/FcntLimitTest.cs
  Tests/Unit/NetworkServer/LoRaDeviceTelemetryTest.cs
  Tests/Unit/NetworkServer/MessageProcessorSingleGatewayTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1266 Print out search TCP/IoT message in case of failures
  Tests/Common/IntegrationTestFixtureBase.Asserts.cs
  Tests/Common/SearchLogOptions.cs
  Tests/E2E/ABPTest.cs
  Tests/E2E/C2DMessageTest.cs
  Tests/E2E/CupsTests.cs
  Tests/E2E/MacTest.cs
  Tests/E2E/MultiConcentratorTests.cs
  Tests/E2E/MultiGatewayTests.cs
  Tests/E2E/OTAAJoinTest.cs
  Tests/E2E/OTAATest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, MacTest, ClassCTest, C2DMessageTest, 1️⃣, MultiConcentratorTest, CupsTest

#1293 Replace `ConversionHelper` with `Hexadecimal`
  AssemblyInfo.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/DownstreamSender.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/HexadecimalExtensions.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaPayloadDecoder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/AppNonce.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/LittleEndianReader.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/NetId.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/NewChannelRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/RXParamSetupRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Utils/ConversionHelper.cs
  Tests/Common/SimulatedBasicsStation.cs
  Tests/Common/SimulatedDevice.cs
  Tests/Unit/LoRaWan/AppNonceTests.cs
  Tests/Unit/LoRaWan/LittleEndianReaderTests.cs
  Tests/Unit/NetworkServer/HexadecimalExtensionsTests.cs
  Tests/Unit/SensorDecoderModule/ConversionHelperTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1179 When forcing a device to use second window, RX1DR and RX1Freq should be omitted
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/DownlinkMessage.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/DownstreamSender.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaOperationTimeWatcher.cs
  Tests/Common/TestUtils.cs
  Tests/E2E/ClassCTest.cs
  Tests/E2E/OTAAJoinTest.cs
  Tests/E2E/OTAATest.cs
  Tests/Integration/CloudToDeviceMessageSizeLimitShouldAbandonTests.cs
  Tests/Integration/CloudToDeviceMessageTests.cs
  Tests/Integration/ConcentratorDeduplicationDataMessagesIntegrationTests.cs
  Tests/Integration/DwellTimeIntegrationTests.cs
  Tests/Integration/JoinTests.cs
  Tests/Integration/ProcessingTests.cs
  Tests/Unit/NetworkServer/BasicsStation/DownstreamSenderTests.cs
  Tests/Unit/NetworkServer/DefaultClassCDevicesMessageSenderTest.cs
  Tests/Unit/NetworkServer/LoRaOperationTimeWatcherTest.cs
  Tests/Unit/NetworkServer/MessageProcessorJoinTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 1️⃣, MultiConcentratorTest, CupsTest

#1303 Add `ReceiveWindowNumber` to represent RX1 and RX2
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/Constants.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilderResponse.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaOperationTimeWatcher.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/ReceiveWindowNumber.cs
  Tests/Common/TestDeviceInfo.cs
  Tests/E2E/IntegrationTestFixtureCI.cs
  Tests/Integration/CloudToDeviceMessageTests.cs
  Tests/Integration/ConcentratorDeduplicationDataMessagesIntegrationTests.cs
  Tests/Unit/NetworkServer/LoRaDeviceTest.cs
  Tests/Unit/NetworkServer/LoRaOperationTimeWatcherTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1320 Upstream data rate is not passed to region
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/Region.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionAS923.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionCN470RP1.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionCN470RP2.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionEU868.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionUS915.cs
  Tests/Common/MessageProcessorTestBase.cs
  Tests/Common/TestUtils.cs
  Tests/Common/WaitableLoRaRequest.cs
  Tests/Integration/CloudToDeviceMessageTests.cs
  Tests/Integration/JoinTests.cs
  Tests/Unit/LoRaTools/DwellTimeLimitedRegionTests.cs
  Tests/Unit/LoRaTools/RegionTest.cs
  Tests/Unit/NetworkServer/MessageProcessorJoinTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1340 Extending CUPS E2E Test with Firmware Upgrade
  .github/workflows/e2e-ci.yaml
  LoRaEngine/modules/LoRaBasicsStationModule/helper-functions.sh
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/CupsTwinInfo.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/JsonHandlers/LnsData.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/Processors/LnsProtocolMessageProcessor.cs
  Tests/Common/IntegrationTestFixtureBase.cs
  Tests/Common/TestConfiguration.cs
  Tests/E2E/CupsTests.cs
  Tests/E2E/appsettings.json
  Tests/Unit/NetworkServer/CupsProtocolMessageProcessorTests.cs
  Tests/Unit/NetworkServer/LnsProtocolMessageProcessorTests.cs
  Tools/Cups-Firmware-Upgrade/fwUpdateSample.sh
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 1️⃣, MultiConcentratorTest, CupsTest

#1352 Move `CheckMic` overloads to each specific `LoRaPayload`
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDeviceCache.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayload.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadData.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinAccept.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinRequest.cs
  Tests/Common/SimulatedDevice.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1356 Make unused raw message a private detail of payload
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayload.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadData.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadJoinAccept.cs
  Tests/Integration/ConcentratorDeduplicationDataMessagesIntegrationTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1359 added new NOTICE file Universal_Decoder_NOTICE 41818
  Samples/UniversalDecoder/NOTICE.txt
Labels: notice

#1371 Fix reversed bytes of (some) MAC commands
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DownlinkMessageBuilder.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaMessage/LoRaPayloadData.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/DevStatusAnswer.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/DutyCycleRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/LinkADRAnswer.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/LinkADRRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/LinkCheckAnswer.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/NewChannelAnswer.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/NewChannelRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/RXParamSetupAnswer.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/RXParamSetupRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/RXTimingSetupRequest.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/TxParamSetupRequest.cs
  Tests/Common/SimulatedDevice.cs
  Tests/Integration/CloudToDeviceMessageSizeLimitShouldAcceptTests.cs
  Tests/Integration/ProcessingTests.cs
  Tests/Unit/LoRaTools/TxParamSetupRequestTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#948 Enable Gateway On the Ci
  LoRaEngine/deployment.ci.aio.template.json
  LoRaEngine/deployment.ci.lns.eflow.template.json
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1404 Allows messages to go upstream when more than 4 concentrators are used
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs
  Tests/Integration/ConcentratorDeduplicationDataMessagesIntegrationTests.cs
  Tests/Integration/DecoderTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 1️⃣, MultiConcentratorTest, CupsTest

#1388 Bug/1032 ensure upstream messages
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs
  Tests/Common/IntegrationTestFixtureBase.Asserts.cs
  Tests/E2E/MultiGatewayTests.cs
  Tests/Integration/DeduplicationStrategyIntegrationTests.cs
  Tests/Integration/ProcessingTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, MultiConcentratorTest, CupsTest

#1444 added new NOTICE file LNS_NOTICE 41993
  LoRaEngine/modules/LoRaWanNetworkSrvModule/NOTICE.txt
Labels: notice

#1443 added new NOTICE file Universal_Decoder_NOTICE 41993
  Samples/UniversalDecoder/NOTICE.txt
Labels: notice
