Repository Azure/iotedge-lorawan-starterkit, pull requests merged in 2022-07, with the labels that each got.

#1746 Running LoRaWAN Network Server decoupled from IoT Edge
  .github/workflows/e2e-ci.yaml
  AssemblyInfo.cs
  LoRaEngine/LoraKeysManagerFacade/ RedisChannelPublisher.cs
  LoRaEngine/LoraKeysManagerFacade/ClearLnsCache.cs
  LoRaEngine/LoraKeysManagerFacade/EdgeDeviceGetter.cs
  LoRaEngine/LoraKeysManagerFacade/FacadeStartup.cs
  LoRaEngine/LoraKeysManagerFacade/FunctionsBundler/DeduplicationExecutionItem.cs
  LoRaEngine/LoraKeysManagerFacade/IChannelPublisher.cs
  LoRaEngine/LoraKeysManagerFacade/IEdgeDeviceGetter.cs
  LoRaEngine/LoraKeysManagerFacade/IServiceClient.cs
  LoRaEngine/LoraKeysManagerFacade/LoraKeysManagerFacadeConstants.cs
  LoRaEngine/LoraKeysManagerFacade/SendCloudToDeviceMessage/SendCloudToDeviceMessage.cs
  LoRaEngine/LoraKeysManagerFacade/ServiceClientAdapter.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/AssemblyInfo.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/BasicsStationNetworkServerStartup.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/BasicsStation/ModuleConnection/ModuleConnectionHost.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/CloudControlHost.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LnsRemoteCallHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LnsRemoteCallListener.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaWan.NetworkServer.csproj
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/NetworkServerConfiguration.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LnsRemoteCall.cs
  Tests/Common/LoRaAPIHelper.cs
  Tests/Integration/DeduplicationWithRedisIntegrationTests.cs
  Tests/Integration/RedisChannelPublisherTests.cs
  Tests/Integration/RedisFixture.cs
  Tests/Integration/RedisRemoteCallListenerTests.cs
  Tests/Simulation/IntegrationTestFixtureSim.cs
  Tests/Simulation/SimulatedCloudTests.cs
  Tests/Simulation/SimulatedLoadTests.cs
  Tests/Simulation/SimulationUtils.cs
  Tests/Simulation/appsettings.json
  Tests/Unit/LoRaTools/ApiVersionTest.cs
  Tests/Unit/LoRaTools/LnsRemoteCallTests.cs
  Tests/Unit/LoraKeysManagerFacade/ClearLnsCacheTest.cs
  Tests/Unit/LoraKeysManagerFacade/EdgeDeviceGetterTests.cs
  Tests/Unit/LoraKeysManagerFacade/FunctionBundlerTest.cs
  Tests/Unit/LoraKeysManagerFacade/MessageDeduplicationTests.cs
  Tests/Unit/LoraKeysManagerFacade/SendCloudToDeviceMessageTest.cs
  Tests/Unit/NetworkServer/BasicsStation/BasicsStationNetworkServerStartupTests.cs
  Tests/Unit/NetworkServer/CloudControlHostTests.cs
  Tests/Unit/NetworkServer/ConfigurationTest.cs
  Tests/Unit/NetworkServer/LnsRemoteCallHandlerTests.cs
  Tests/Unit/NetworkServer/LoRaDeviceCacheTest.cs
  Tests/Unit/NetworkServer/ModuleConnectionHostTest.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, MacTest, ClassCTest, C2DMessageTest, CloudDeploymentTest

#1772 fix: e2e-ci pipeline
  .github/workflows/e2e-ci.yaml
Labels: fullci, SensorDecodingTest, OTAAJoinTest, MacTest, C2DMessageTest, MultiGatewayTest, CloudDeploymentTest

#1775 added new NOTICE file LNS_NOTICE 45936
  LoRaEngine/modules/LoRaWanNetworkSrvModule/NOTICE.txt
Labels: notice

#1776 fix: Redis cache not properly updated because of IoT Hub query results delay
  .github/actions/deployedge/action.yml
  LoRaEngine/LoraKeysManagerFacade/LoRaDevAddrCache.cs
  LoRaEngine/LoraKeysManagerFacade/LoRaDeviceJoinNotificationFunction.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/JoinRequestMessageHandler.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDeviceAPIService.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDeviceAPIServiceBase.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/CommonAPI/DeviceJoinNotification.cs
  Tests/Common/TestMessageDispatcher.cs
  Tests/Integration/CloudToDeviceMessageTests.cs
  Tests/Integration/DevAddrCacheTest.cs
  Tests/Integration/JoinRequestMessageHandlerIntegrationTests.cs
  Tests/Integration/ProcessingTests.cs
  Tests/Unit/NetworkServer/JoinRequestMessageHandlerTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, ClassCTest, C2DMessageTest, MultiGatewayTest, 1️⃣, 2️⃣, 3️⃣, MultiConcentratorTest, CupsTest, LnsDiscoveryTest, CloudDeploymentTest

#1689 Add IDeviceTwin interface + IoT Hub Device Twin wrapper on it
  LoRaEngine/LoraKeysManagerFacade/CreateEdgeDevice.cs
  LoRaEngine/LoraKeysManagerFacade/FacadeStartup.cs
  LoRaEngine/LoraKeysManagerFacade/LoRaDevAddrCache.cs
  LoRaEngine/LoraKeysManagerFacade/LoraKeysManagerFacadeConstants.cs
  LoRaEngine/LoraKeysManagerFacade/SendCloudToDeviceMessage/SendCloudToDeviceMessage.cs
  LoRaEngine/LoraKeysManagerFacade/TwinExtensions.cs
  LoRaEngine/modules/LoRaWan.NetworkServerDiscovery/TagBasedLnsDiscovery.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/IDeviceRegistryManager.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/IDeviceTwin.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/IoTHubImpl/DeviceTwinExtensions.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/IoTHubImpl/IoTHubDeviceTwin.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/IoTHubImpl/IoTHubRegistryManager.cs
  LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/TwinPropertiesConstants.cs
  Tests/Common/IntegrationTestFixtureBase.cs
  Tests/E2E/LnsDiscoveryTests.cs
  Tests/Integration/DevAddrCacheTest.cs
  Tests/Integration/LnsDiscoveryIntegrationTests.cs
  Tests/Unit/IoTHubImpl/DeviceTwinExtensionsTests.cs
  Tests/Unit/IoTHubImpl/FakeIoTHubDeviceTwin.cs
  Tests/Unit/IoTHubImpl/IoTHubDeviceTwinTests.cs
  Tests/Unit/IoTHubImpl/IoTHubRegistryManagerTests.cs
  Tests/Unit/LoraKeysManagerFacade/ConcentratorCredentialTests.cs
  Tests/Unit/LoraKeysManagerFacade/ConcentratorFirmwareFunctionTests.cs
  Tests/Unit/LoraKeysManagerFacade/DeviceGetterTest.cs
  Tests/Unit/NetworkServerDiscovery/TagBasedLnsDiscoveryTests.cs
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, ClassCTest, C2DMessageTest, MultiGatewayTest, 1️⃣, CloudDeploymentTest

#1789 added new NOTICE file LNS_NOTICE 46239
  LoRaEngine/modules/LoRaWanNetworkSrvModule/NOTICE.txt
Labels: notice

#1791 fix: Adjust mismatch of Basic Station tags in CI
  .github/actions/deployedge/action.yml
Labels: fullci, SensorDecodingTest, OTAAJoinTest, ABPTest, OTAATest, MacTest, C2DMessageTest, MultiGatewayTest, 1️⃣, MultiConcentratorTest, CupsTest, LnsDiscoveryTest, CloudDeploymentTest
